### ISSUE TITLE
new PDF file has proper bookmarks but blank content

### ISSUE THREAD

**Issue by willywutang** [RussellLuo/pdfbookmarker#6]
When I run:

`pdfbm x.pdf bookmarks.txt`

the output file `x-new.pdf` is created which has the bookmarks in the right places, but the content in the pdf itself is blank.

**Comment by willywutang** [comment]
Note: This issue occurred for me on Mac OS X, but did not occur from me on Ubuntu.

**Comment by stdAri** [comment]
This issue also occurred on Ubuntu 18.04.
The output file only has the bookmarks.

**Comment by TobyYoung0412** [comment]
This issue also occurred on Ubuntu 18.04.
The output file only has the bookmarks.

**Comment by NoelOfTheWildIsle** [comment]
macOS Mojave 10.14.4 the bookmarks are inserted at the right spot but all the text and images are stripped out. A 7.4MB pdf becomes a 40KB PDF with bookmarks.

**Comment by RussellLuo** [comment]
Hi @willywutang @TobyYoung0412 @tapcontinue, could you guys provide some details of your Python environments:
- the version of Python
- and the version of the libraries (e.g. the output of `pip freeze`)
- or the PDF (could be very helpful)

**Comment by NoelOfTheWildIsle** [comment]
Python 3.7.2

Pip3freeze:
asn1crypto==0.24.0
astroid==2.1.0
autopep8==1.4.3
bcrypt==3.1.5
beautifulsoup4==4.7.1
bottlenose==1.1.8
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
cryptography==2.4.2
Cython==0.29.6
et-xmlfile==1.0.1
eyeD3==0.8.9
Fabric3==1.14.post1
fpdf==1.7.2
idna==2.8
invoke==1.2.0
isbn-hyphenate==1.0.4
isort==4.3.4
jdcal==1.4
lazy-object-proxy==1.3.1
libmagic==1.0
lxml==4.3.3
mccabe==0.6.1
openpyxl==2.6.0
paramiko==2.4.2
pathlib==1.0.1
pdf2image==1.4.2
pdfbookmarker==0.3
pdfCropMargins==0.1.4
pdfkit==0.6.1
pdfoutliner==0.0.3
pep8==1.7.1
Pillow==5.4.1
pyasn1==0.4.4
pycodestyle==2.5.0
pycparser==2.19
pylast==2.4.0
pylint==2.2.2
PyNaCl==1.3.0
PyPDF2==1.26.0
pyperclip==1.7.0
python-magic==0.4.15
requests==2.21.0
selenium==3.141.0
six==1.12.0
soupsieve==1.9
UNKNOWN==0.0.0
urllib3==1.24.1
virtualenv==16.2.0
wkhtmltopdf==0.2
wrapt==1.10.11

xtopdf, PDFwriter, FPDF, wkhtmltopdf, pdfkit, lxml, beautifulsoup4, cython, & cffi were installed long after I played with pdfbookmarker and can't be the source of a conflict. 

Further, to ensure it was not a pip conflict, I make a virtual environment and only installed pdfbookmarker and got the same results. It wasen't a single PDF that had this issue.  Any PDF I used had the same result. I'm sorry I can't include the PDF as I don't own the distribution rights but here is all the info I can pull from PDFInfo:

Creator:        pdftk 2.02 - www.pdftk.com
Producer:       itext-paulo-155 (itextpdf.sf.net-lowagie.com)
CreationDate:   Wed Apr  3 15:46:35 2019 CDT
ModDate:        Wed Apr  3 15:46:35 2019 CDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          52
Encrypted:      no
Page size:      648 x 864 pts
Page rot:       0
File size:      257776691 bytes
Optimized:      no
PDF version:    1.4

Hope that helps!

**Comment by RussellLuo** [comment]
Per [Merge 2 pdf files giving me an empty pdf](https://stackoverflow.com/a/49927541/963379), the reason is as follows:

> The problem is that you're closing the files before the write.
>
> When you call pdfMerger.append, it doesn't actually read and process the whole file then; it only does so later, when you call pdfMerger.write. Since the files you've appended are closed, it reads no data from each of them, and therefore outputs an empty PDF.
>
> This should actually raise an exception, which would have made the problem and the fix obvious. Apparently this is [a bug introduced in version 1.26](https://github.com/mstamy2/PyPDF2/issues/263), and it will be fixed in the next version. Unfortunately, while the fix was implemented in July 2016, there hasn't been a next version since May 2016. ([See this issue](https://github.com/mstamy2/PyPDF2/issues/385).)
