### ISSUE TITLE
Offsets is not working

### ISSUE THREAD

**Issue by SecretgardenA** [RussellLuo/pdfbookmarker#9]
adding '//+13' just does nothing, the first bookmark still points to first page, no offset 

//+13
+"第1章 熟悉LATEX"|1 
++"1.1让LATEX跑起来"|2 
+++"1.1.1 LATEX的发行版及其安装"|2 
++++"CTEX套装"|3 
++++"TEX Live"|7 
+++"1.1.2 编辑器与周边工具"|13 
++++"编辑器举例—TeXworks"|13 
++++"PDF阅读器"|18 
++++"命令行工具"|21

**Comment by RussellLuo** [comment]
I guess you are using [pdfbookmarker 0.5.0](https://pypi.org/project/pdfbookmarker/0.5.0/), which does not include the "Offsets" feature.

Try the latest source code from this GitHub repo instead. I'll release 0.6.0 soon.

**Comment by SecretgardenA** [comment]
Yes, it works now. Thank you!
